### ISSUE TITLE
AWS integration fails to create the integration and rolls back cloudformation stack with Internal failure.

### ISSUE THREAD

**Issue by dogfish182** [DataDog/datadog-cloudformation-resources#236]
**Describe the bug**
AWS integration fails with obscure error

**To Reproduce**
run a template that looks like this

```
Resources:
  DatadogAWSDatadogIntegrationAWS:
    Type: Datadog::Integrations::AWS
    Properties:
      AccountID: '123123123123'
      RoleName: shared-datadog-aws-integration
    Metadata:
      aws:cdk:path: mystack/DatadogAWSDatadogIntegrationAWS
  DatadogRoleF31A7099:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId:
                  Fn::Join:
                    - ''
                    - - '{{resolve:secretsmanager:arn:'
                      - Ref: AWS::Partition
                      - :secretsmanager:eu-west-1:123123123123:secret:DatadogIntegrationExternalID:SecretString:::}}
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::464622532012:root
        Version: '2012-10-17'
      Description: Datadog integration for aws monitoring
      PermissionsBoundary:
        Fn::Join:
          - ''
          - - 'arn:aws:iam::'
            - Ref: AWS::AccountId
            - :policy/base-permissions-boundary
      RoleName: shared-datadog-aws-integration
      Tags:
        - Key: tag
          value: tag
    DependsOn:
      - DatadogAWSDatadogIntegrationAWS
    Metadata:
      aws:cdk:path: mystack/DatadogRole/Resource
  DatadogRolePolicy6CE03EE3:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - alldatadogstuffasperdocs
            Effect: Allow
            Resource: '*'
        Version: '2012-10-17'
      PolicyName: shared-datadog-integration-policy
      Roles:
        - Ref: DatadogRoleF31A7099
```

**Logs**
```
1:36:58 PM | CREATE_FAILED        | Datadog::Integrations::AWS                  | DatadogAWSDatadogIntegrationAWS
Resource handler returned message: "" (RequestToken: 16b2f5a7-3d09-738e-76ae-33db3a6ad5b8, HandlerErrorCode: InternalFa
ilure)


 ❌  account-bootstrap-stack failed: Error: The stack named account-bootstrap-stack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "" (RequestToken: 16b2f5a7-3d09-738e-76ae-33db3a6ad5b8, HandlerErrorCode: InternalFailure)
    at FullCloudFormationDeployment.monitorDeployment (/Users/me/code/place/project/node_modules/aws-cdk/lib/api/deploy-stack.ts:505:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at deployStack2 (/Users/me/code/place/project/node_modules/aws-cdk/lib/cdk-toolkit.ts:265:24)
    at /Users/me/code/place/project/node_modules/aws-cdk/lib/deploy.ts:39:11
    at run (/Users/me/code/place/project/node_modules/p-queue/dist/index.js:163:29)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named account-bootstrap-stack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "" (RequestToken: 16b2f5a7-3d09-738e-76ae-33db3a6ad5b8, HandlerErrorCode: InternalFailure)
    at deployStacks (/Users/me/code/place/project/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/Users/me/code/place/project/node_modules/aws-cdk/lib/cdk-toolkit.ts:339:7)
    at initCommandLine (/Users/me/code/place/project/node_modules/aws-cdk/lib/cli.ts:374:12)

Stack Deployments Failed: Error: The stack named account-bootstrap-stack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "" (RequestToken: 16b2f5a7-3d09-738e-76ae-33db3a6ad5b8, HandlerErrorCode: InternalFailure)
```

**Expected behavior**
The cloudformation should run to completion. 
I expect the account integration to enable the account in datadog (this does occur)
I expect the secret to be written to secrets manager (this does NOT occur)
I expect my role to be created which I pull the secret from secrets manager (this does NOT occur)

**Environment and Versions (please complete the following information):**
Datadog AWS Integration 2.2.1
I am generating cloudformation via cdkv2 however I doubt this is relevant as I've included the generated cloudformation template above (which is run and faults).

**Additional context**
It essentially looks like the cloudformation handler is swallowing the error, which makes it very hard to troubleshoot this. 
I've also logged a ticket with datadog support.

**Comment by dogfish182** [comment]
I can still reproduce this issue as shown in the orginal post.

**Comment by flavioelawi** [comment]
We are facing the same error (although on Monitor and Dashboards)
We have a support case open with AWS

**Comment by flavioelawi** [comment]
Thanks we just did the same, lets see what happens

**Comment by skarimo** [comment]
Thanks for opening this issue. We are going to merge and release the change https://github.com/DataDog/datadog-cloudformation-resources/pull/257 which should catch any unhandled exceptions in the resources them selves. 

However, this wouldn't expose all errors mainly because AWS does obfuscate logs/events quite heavily on their end so things such as bad type configuration and bad execution roles would still fail in non-obvious ways. Which I suspect is the reason for the failures you are seeing @flavioelawi with dashboards and monitors

**Comment by flavioelawi** [comment]
We have resolved our issue; 

our execution role already had the correct trust policy:
```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": [
                    "resources.cloudformation.amazonaws.com",
                    "cloudformation.amazonaws.com"
                ]
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

And a policy to allow access to the Secrets and its Kms key
```
        {
            "Action": [
                "secretsmanager:GetSecretValue",
                "kms:Decrypt",
                "kms:DescribeKey"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },
```

We also added the `CloudWatchLogsFullAccess` managed policy to allow for the integration to push logs to Cloudwatch logs (but its log group is still empty, I guess for another issue)

The issue in our case was a typo in the dynamic reference, where we were missing the `SecretString` part before the Json attribute selector.

@dogfish182 in your case you are missing `external_id` from your dynamic reference at the end, [this is what is setup by the integration lambda/code](https://github.com/DataDog/datadog-cloudformation-resources/blob/master/datadog-integrations-aws-handler/src/datadog_integrations_aws/handlers.py#L97)

Also some feedback:

* It would be useful to know for each integration, what kind execution policy and trust policy is expected in the execution role.
* I can't find it anymore, but was there a github issue in the upstream aws/cloudformation project about LogConfiguration not working?

**Comment by skarimo** [comment]
We released the AWS resource version 2.4.0 that should capture and return any unhandled exception on the resource it self. However, as mentioned previously, errors swallowed by AWS would probably still not be captured by this change as it happens outside of the resource handler.
